### ISSUE TITLE
demonstration code is not working

### ISSUE THREAD

**Issue by stellarkey** [onyanko-pon/nginx-access-log#1]
Run it with error as following:
```bash

import { parse, digest } from 'nginx-access-log'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
```

I googled a lot, tried to use some like (as in [https://github.com/mochajs/mocha/issues/4531](https://github.com/mochajs/mocha/issues/4531))

```javacript
import pkg from 'nginx-access-log';
const { parse, digest } = pkg;
```

Or add `  "type": "module",` into `package.json`...

But the functions are missing, still.

Dont know how to make this module work.

Is there a solution?

**Comment by stellarkey** [comment]
Downloaded your source code and encountered with the same eroor. QAQ

**Comment by mrymam** [comment]
Hi @stellarkey ! Thank you for building issue!

I found a mistake of main path in `package.json`. 

I fixed in the following pull request.
https://github.com/onyanko-pon/nginx-access-log/pull/2/files

I have updated the version. Reinstall [this package](https://www.npmjs.com/package/nginx-access-log) and try!

I'm sorry for my mistake.

**Comment by mrymam** [comment]
And I have update sample codes in `REAME.md`.
If you use Node.js (without TypeScript), use `require('nginx-access-log')` instead of `from 'nginx-access-log'`

**Comment by stellarkey** [comment]
Thanks! it works now.
